### ISSUE TITLE
public repo on new career path as art critic

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/public-xar-repo#23]
for some mysterious reason, public repo now uses `[appname].png` to serve icons for recently uploaded apps. see dashboard and the docs below, icons are also no longer displayed when installing via package-manager
![screen shot 2018-06-08 at 13 28 11](https://user-images.githubusercontent.com/6205362/41155967-49436f98-6b20-11e8-98c6-cb6f7c25d8de.png)

this is a bug, icon.png in its usual location should still be used.

**Comment by JoernT** [comment]
@duncdrum sorry to say that but though creative this issue title does not help to identify what it's about.

**Comment by duncdrum** [comment]
[seems fixed](http://demo.exist-db.org/exist/apps/public-repo/index.html), still not sure what went wrong though

**Comment by dizzzz** [comment]
@duncdrum please use more clear titles for future reports, as Joern said, the title is rather unclear.
